** CAP 一次深度的思考
1，我对自己在公司，能做想做的事情，可能考虑有点多。想的多，有可能才能做的多，做的多，不一定想的多。
我在公司也决定不了什么事情。公司的迭代太慢了，决策有点问题。

2，不管去哪家公司，你永远就是做你能做的事，在此基础上再想一想。还有一个维度是钱，之前我自己在小公司，
本质上不是为了钱，而是为了能想多一点，现在如我所愿，我想的比较多了。想的多，也积累了一些思考，去大公司
做一个专业的事情，你没有时间，没有空间在一些单纯的工作之外的事情上，至少在制度层面，不需要你去操心，
小公司最大的问题在制度层面，有一些简单的道理不一定能推进开，不一定大家都能接受。小公司思考的问题是制度
从哪里来？这里所说的制度是正确的制度。另一个维度是个人价值问题，你做什么样的事情才有价值？这个和你善于做什么
事情都有关系，说实话，大多数人都不知道自己善长做啥，一般你喜欢的事情就是你善于做的，但是中年人经常面临的问
题是做最赚钱的事情。我最喜欢做的事情，是去完成一件事情，且思考，这个是我一生的事情。但是完成一件事情，有
很多因素影响，有一些你能够控制，有一些你不能控制，在一个圈内，你能否把一件事情做好，做好的标准能否自洽？
就是说一件事情你在圈内，自已的标准内做好了，那结果就是好的。不然你认为你把自己做好，结果确是坏的，然后受到
别人指手画脚，这样就没有了自我，没我了激情。所以做一件事情的思路是，我的价值是什么？我可以在这个闭环内实现
有激情的干活吗？如果有，再看钱的因素，要可控。

3，职业生涯因素，人生好像没有人能预测自己最终妥协权衡的结果，所以，职业生涯的伪命题是：你想去一个平台，并且为
下一个平台，做准备，那你知道下一平台是什么吗？或者说你想去的这个平台，真的能为下一平台做准备吗？还有就是这个
平台，真的能为你提供自己的时间吗？真的能给你提供人生的思考吗？你的方向是否受限于公司的制度，主管？你真的理解
你想去的那个平台的逻辑吗？知之为知之，不知为不知。所以做一个事情要在制度可行性上没阻碍，要在硬实力上也要没有阻碍。
所以单从职业生涯上来说，很多人是没有职业生涯或者职业生涯很容易就到头了。

4，以上因素因人而异，有些人或许就从来不想，人活着到底是为了什么？自己一生的目标在哪？自己的下一个储备点在哪？
在形成公司制度，这个人的因素必须要考虑。事情不是说我想怎样就怎样的，一切都是控制的学问。一切都朝着钱其实挺没意思，
钱其实也不是人的最终目标。
<2020-04-25>
