* smartisan note
** 有时真的不明白，生活到底为了什么？目标是如此的模糊，没有确切的路径。
EOSIO
** 从前总是太自负，很多事在没有尝试感受就坚持，比如女人，做事方法。
** 所谓充实无聊，人希望充实，充实是欲望自信，人们总是在表达欲望，人们却拒绝思考，拒绝绕弯，欲望是直接的，思想是自由的。
在当下也不知道自已能做要做哪些事情。只是这样坚持着，希望从中找到满足。这就是常态，这就是我。
** 又是一年，自已可以庆慰的是又勇敢了需多，黑夜的润泽给了我许多遐想，自已和以前有一些感受却从未变化，我就是我，我必需接受我，融洽的接受我的一切。今年长痔疮了。
** 抄诗
** 写在2017年春节，大年三十。
每年的过年都会感触良多。甜甜更加长大。家里也添置了不少东西。周遭的亲人的生活处境也改变了很多。不变的是过年的那种总结感。变化大于不变。
还在感叹假期的短暂。还在感叹人情世故。时光的变迁。岁月的流逝。希望我能明白这其中生活的奥秘。。
过年就是不同地方的人，归回原点。，做一件纯粹为了家人快乐的事。是团聚。
** 选择做自己选择的事

不要停止选择，再微博和视频里无法自拔
** 弗洛伊德 学说 观点

精神困顿是应为状态或环境的不好还是因为选择了不思考（不想）
by the way ，不想并不一定是坏的，如果能控制自己去想自己想的，控制不饿多想，那也是极好的。get inner peace

思考的层次化，思考中追逐层次化的作用？对于我来说，我是一个做事喜欢讨巧的人，出一分力想干成两份事。层次化的思维会很讨巧，针对性的思考，拉高一个层面来想，使我越想越赚，从而刺激我思维清晰。

所以这个原理可以回答为什么游戏使人容易沉醉，获得满足感。我的游戏就是层次化思维。

层次化思维比较累的地方，是捕捉当前问题，准确问题，然后思考结果。

当然思维最终还是要记录，不然想过没记下，有点划不来。
层次化思维也是一个挖掘自己的过程。在挖的过程中希望能够获得清晰的认知，最终返回到我一直想获得的清晰。

 如果一个问题想的很累，那一定是挖不出，强挖就是笨，就是停滞。

选择很重要，转变也很重要。

工作时的思维模式比较固定，因为面对的问题都是专业内的一些问题，能力基础素质不是最重要的，思维陌生和形态是最重要的。思维模式和形态才是真正的所谓的擅长于不擅长。

思维模式和心态一个长期的综合的积累。

层次化思考过程中的代表其实就是找到挖掘问题，当挖到问题时，答案其实早就有了。

思维模式和心态的高度的觉定性因素是坚持自己的坚持，和公平看待世界的看待。

思想是早沉浸还是要连续？
** 青山裕企，腿很细
** 滴露松木 洗手液  好闻
** 感觉精力好的时侯总想写点什么，感党这是一个自我学习的过程也是一个自我思考的过程。似乎一些有趣的人，他们有一个共同的特点，就是经历过文字的磨炼，懂得用文字思考。如微博上的作业本，韩寒，冯唐。这个事实我现在才明白。以前总是错误的认为，只有数学物理等理科的东西才代表思考，现在想想错误大发了。
** 每一个这样的早晨，都是在这样的上班路中度过，岁月，年岁，蹉跎而恍惚。没有办法的事。
<image w=858 h=1157 describe= name=Notes_1457395581434.jpg>
** 真野惠里菜
** 思考，最近的心情很差，主要是感觉前路无望，或说世界物欲横流，我只是一页扁舟，为何那么多混的比我好人，为何我无力买房，房价却任性的涨？
其次，为何老婆找工作这么难？花那么多钱培训，出来还是这个样子。
** GVG-118
** cozmo机器人
** 总是在幻想，不切实际
<image w=858 h=1157 describe= name=Notes_1458348961857.jpg>
** IO.or
我的名字
** 好吃的东西  
冰可乐 小西红柿
** 张丹于 科大师兄，华为工作十年。华为图灵部门
** 29,年前一天，在回家的火车上，心里年味酝酿已久，放眼窗外，乡村风景和老家一样，不由观察。
此时，村落青山和老家的一样如记忆中亲切，不同的是，原以为过年的那种热闹，在从火车上往下看不出，也许是就算热闹从高往下也是不能察觉出，只看到，乡村小径上后座载着人的摩托，我想都是小两口。下午了，河边依旧去早晨忙碌的洗漱。
平常也有摩托，但后座没人，平常下午应该就没什么人了。
** 回家稀里哗啦，不明青红皂白的有一顿，回家本来心情兴奋，老婆确实心里有包袱，我也被拽下去。妈蛋，世事不难预料，却是难处理。到时回家想必情况不好说。哎，过个屁年！
** 今天正月初五，芳芳出嫁，宝宝会叫妈妈，会嘴里哺啦吥啦的叫。看见红皮就要，小指头到处扣，会摇头，要的东西会嗯。
** 书单
白色流淌一片
** 保持思考，冷静很重要。处理好自己的精力和专注度，不要疲惫和分散。前脑控制后脑，让机智控制想象，让思考控制感觉。
** 我是一个平凡的人，我要安静的接受这一切。这是我接受这个世界的根本看法。如果还心里不服的话，那这么说会好点，我可能是一个平凡的人。
** 人的一生，心里安静需要不了太多钱，需要明白自己的心，安置好内心。
** 这个世界需要你，即要拥有想象力，又要草根。即要相信一切皆有可能，又要明白生活可能一成不变。总之要拿得起，放得下。追求安全感，又要冒险
** 尊重对手，面试面的不仅是技术。
面试中如果面的是公司，如华为这样的，做人很重要。
如果是创业公司老板面，那自信很重要。
** 吃
珍妮曲奇
** 一个好心态是要积级的，要能感受到这个世界的美好。伸缩有度。
** 寻找一个真实可以依靠的世界
** 一部分是情感一部分是智商，这两项都很重要，但问题是智商要在情感的控制下才能发挥良好的作用，控制情感才是最重要的，这需要很好的智商才能达到。
** 翠玉花满地
轻灵动飞舞
** 

































