* from onenote
**  回去的路上
外公去世了，我亲爱的人，在生之时以为会怎样怎样，将死之时却又是另一番光
景，人生并没有按照我们之前非常确认的轨迹发生，甚至有些凄凉，聪明一世，
糊涂一时？还是没有用发展的眼光看问题，生前的信示旦旦？是我们变了还是原
来就没有看出来。被骗和没看出来之间的差距几乎变有，对于一个信受承诺的人
来说，每一个承诺相当于都是在骗人。
** 除了思考，还有记忆
之前的想法中，太注重思考，而忽略了记忆，其实记忆和思考并驾其驱，想达到
专业，记忆非常重要。想达到聪明，思考加感受就可以。
** 什么是学习
所谓学习就归一化简单化，学会的人总会觉得一个事件非常简单。
** 系统化的思路
就目标来说任何一项现有工作中的事情，最好的运作方式都是要有系统化的方案，
系统化的好环直接决定了结果的好坏。系统化的目标是指向一件具体事情的结果
的，结果应做成什么样子，那么系统化就朝哪个方向努力。

同时一个人其实就是一个多方面的系统，做人，做事，看法等，你在牛人身边能
感觉到，就会学习这种做法，学习系统的因为你想改善一个系统总是要花大量时
间，比预想的多，就如把一个搓人变成一个牛人一样，不是一两件事情能搞定的，
就如品味。系统优化也是努力和思考的目标。
** 脑洞与游戏
大部分暴孽之气来自于想不劳而获。人不能涉猎太多领域，否则达不到专一，因
为无论什么领域，只要有很多人参与，那么这个领域都会形成一个系统，必须去
耕耘，去细化才能搞定。如果涉入的领域能有助激发思考才行，而不是一味的开
脑洞，脑洞不能开多，游戏不能开多，现实中收获才是成就与充实的来源。你天
份好，但是不努力，就等于没用，因为还没发现我天份能好到睡觉也能发财的地
步。Keep moving! Keep thinking and feeling!
** 有我自已，也有工作，也有生活
好的思维的状态就是，有我自已的意识，能够对工作感兴趣，也能能有生活（欲
望，这两个基本等同。）
** 挑战精神
挑战精神不是反智的，同时挑战精神代表着多try，对一个人的人生很重要。但
是盲目的挑战就是脾气了，并且反智。

所以挑战需要很好的平衡。

挑战精神与智力思考是平行的一个维度。
** 所谓人生格局
一直不怎么信这些大的成功学词汇，虽然有这个词。我不相信成 功学的原因，
是他们太浅，永远只说现象，虽然他们总结的现象确实很像。其中就有如:人生
格局，坚持等。

换个角度思考，其实人生格局，我觉有的话，那只能说是心理了。大多数时候一
些事情的结果没有负面心理来的糟糕，如果你选择了人生格局，那么你选择的是
看轻那些事情的结果，而好好的控制负面心理。这样是不是你整个人看起来都不
一样。
** 思维过程
思维过程大致可以分为三个阶段：
	1. 收集，感受
	2. 思考因果，猜策联系，有效推断。
	3. 升级简化结果，记忆结果，形成发现。

简化版本：
	1. 收集，感受
	2. 因果，方向
	3. 结论
** 人的思考与成长
人的大部分时间都是困境，从整体上来说。对于人生的大的决则理解进步非常之
缓慢，我之前有一个理论就是人的性格，30岁以后就不要期望它改变。性格来自
于对于人生的理解。

我是一个懒惰的人，不勇敢的人，对于人生我总是能逃则逃，这些大的我一时难
以想透的问题，不去攻。喜欢小聪明，但小聪明总归是小，收获也小，也有很大
的限制性，总有瓶胫的一天。

小聪明还体现在，我喜欢一些专业性的，小范围的东西。

以上东西都是在我思考感受自己的过程之中想出来的。

人生要活的让自己开心，不紧绷，放松去体验。这种情况下才会有真实感爱，真
实的感受让你看清世界，看清世界，不能光靠眼睛。

我是一个紧绷的人，这点希望可以改变。

我太相信自己的眼睛了。
** 坚持书写
书写是一种思考方式，坚持书写，是学会表达。心中一直的顾虑是要用什么工具？
Onenote/emacs/锤子便签? 还有就是没有完全面对自己，拿起笔记本来又不知道
说什么。写下的都是开机之前的想法。一旦开始写了，很多焦虑感就没有了，我
自己也在想这是为什么？

思考是要有自由度的，没有自由就没有思考，对着电脑写东西的时候，我太专心
于写了，无法面对自己的自由想法。我有其它的想法，但都被写这个行为给覆盖
了。一方面是因为拿着电脑的时候，总想着用电脑做点什么，突破点什么。

还有就是我认为写作不能是平铺直叙，不简要，没有重点，但现在我只要一简练
就没办法发散。不简练的时候会说出很多的废话。

现在的我还没有一个很好的思考系统，没有达到我心目中感觉到的那个真正会思
考，想的很清楚的状态。

现在的我只是有一些思考点， 这些点在脑海中，暂时自己摆到重要的位置。试
图把问题列出来。

思考点：容易紧张，自我隐私感，不得专的现状，思考之外灵敏的感官，性，
power,个人安逸的爽与勇敢的改变，这个二手iphone该不该留，坚果pro2该不该
再买一个，折叠浴缸该不该买，我应该为下一份工作准备什么，我应该为拼弃自
身局限性远离父母，面对自已是思考的源泉但太多的面对自己说出来会不会不心
安，书写时候注意怎样的标点符号以明确表达，我应该把自己坚持起来吗还是灵
活一点，断舍离经常会忘如何保持洁僻避免性价比带来的性不行，我很容易沉浸
于自己的想法之中导致我意识不到体系之外的东西，心安看来是爽但是不凑效，
不心安常的我非常怒，怒本身是一种气自己不能，不要脸脸贴上现实是不是才能
贴近现实，有时就没有表达的欲望表达是愤怒的没愤怒就没有表达，我只理解最
浅显的道理因为那看起来最像是对的不相信不能被简化的东西，生活有时就是在
避免沮丧有时是为了不接受自己而去努力证明自己以期望自己对自己的看法是对
的，人和人本来就不一样不一样的还有后天的拧巴人若是不拧巴很享受并且能享
受自己的生活那么这个人的先天能力就能发挥如果拧巴了这其中对于自己的相信
就非常的重要，狐独为什么很重要狐独能自己面对自己与自己面对朋友是不一样
的自己面对朋友没办法全部敞开就会跑偏平常面对生活时我们往往会把自己忘掉，
生活中自己怎样最令自己满意是物质状态吗不是是勇敢的自己是一个让自己都尊
敬的自己是一个选择说与不说的自己 表达的时候面对自己不表达的时候面对他
人，不崇拜自已来尊敬自己 这样思考任何时候都可以发生 而不用再委屈自己，
自己永远面对的只是自己 这世界只有自己的迭代 本质上没有他人，怎么面对自
己 平静 感受冲突 文字 理解 清晰，思想上的懒惰导致追求安宁 因为安宁不需
要面对冲突解决问题 这样就可以很快乐 但是冲突是客观存在的 不去解决就没
安宁 我本人的终级陷阱 看起来是要平静的解决冲突 用佛家的话说 就是要平常
心看待一切 包括不平常看待本身。

急和忙是上天赋予的，不是老板，至少在那个状态下不是，面临急事和忙事时，
压力感是自己选择的，人不能为了压力感而活，那是动物性，人要活成超我。这
也是面对自己的方法。

我很强吗？答案是我强到爆炸，只可能在一些事情上不强，最终会强到爆。
** 4句名言- by lzh
	• 不能控制欲望和欲望本身没有关系，欲望是好的，而不能控制欲望是
	坏的。

例子：比如你不想守诚信，而想骗人去或取钱财时，这时候欲望是钱财。这个问
题本身不在于钱财或是欲望，钱财和欲望本没有错。错的是你本想守诚信，却没
能守住。不能控制欲望是错的。欲望本没有错，凡人皆有七情六欲，这里不说一
些极端例外。

	• 比起坏的结果本身，那些因为坏的结果产生的负面心理更差。例子：
比如你极为害怕某个考试失败，而出现了极为紧张的心理，其实问题在于你把考
试结果的重要性放在了比负面心理重要的位置，不能说不出现负面心理，但是负
面心理有时过大会产生极为不好的影响。有时候人生态度放高一点，那些结果之
后看起来实在没那么重要，因此大多时候我们都是把结果看得大于负面心理。大
多时候，没有了这些负面心理，就成为了人生赢家。

	• 我只是认真，我只是思考，和我是不是紧张或者害怕并没有关系。如
	• 何给自己一个更好的可思考环境。
** 思考自身
思考，感受本身是最重要的事情，去澄清一些本质和内心底的细小声音。思维天
生具有发散性，但完成一件事情又需要专注性。发散性不可或缺，因为它是解决
问题时，寻找途径的自然行为，如果没有发散性问题就不可能解决，专注性就是
把一发散性控制在这个事情上。如果生硬的控制大脑，使得自己专注于一个事情
上，往往阻力很大，因为这种不情愿的控制伤害了大脑的天然发散性，即如果这
个事情你不喜欢，大脑会自动发散去寻找其它你喜欢的事情。但如果这相事情是
你热爱的，是你喜欢，那个大脑就会集中在上面，而且可以获得在这个事情上很
好的发散性。
** 思考中带有一个思考方法
每次思考一个问题，首先是要静下来思考，找出一个有效的思路和最好的思维辅
助工具。好的思维的标准是：1，能够往思维清楚的方向走。2，思维具有可叠加
建设性，一点一点的慢慢思考就能够把问题解决。3，最终目标是，越清晰越好，
化简为最有趣最简单的理论。
** 安全感，沉稳心态，心理与游泳
有时候是要能按纳住内心的各种湧动的心理，沉静下来真的想想，客观的想想。
就好比，敢于在水深的泄里游泳，要对水放心，不慌，不急，不忙。
** 想的太多
有时候思考来思考去，也想不出个什么名堂，心情很压抑，找不到刺激方向和点。
这时候，我想起了王老师，正直牛逼的人是什么样子，其实就是去做。很多时候，
在你还在没反应过来的时候，他已经把事情做完了。
** 读书的作用
技术需要专一，沉入式的思考。而读书思考的是整个人及世界。
** 思考，训练，自由，欲望，感觉，兴趣，心态
人群效应心理效应心态---就是一个能够思考的环境！人是可以笨死的！其实事
实就在那只是你看不见！对于笨人好像没有同理心！训练是更加从容，有一个更
好的心态！
** 重提品位与人生视角
今天看了王垠的blog，其中提到其父给他取王垠，音同
** 思考
我之前说过要：
	1. 分角度思考。
	2. 分层次思考。
	3. 要有跨度，先总体做一做，不要有怕难怕懒的心理。
	4. 如果有心理障碍，先将心理想清楚，后想事。
	5. 思想要自由，没有什么不可心想，但是有一些是不能做。
	6. 虽然思考自由，但不代表思想不可控，要有可控的思维。
	7. 要肯深入，肯记忆，肯转变跨度。
	8. 一个时间点尽量将事情简单化。
** 很重要
	• 享受被操的感觉，不偏执但积极。记忆很重要，记忆和思考要须毛搂。
	• 要能克服偏执，思想上能够安定。
** 担心与负面心理
最近总是焦虑，感觉自已太穷了，没钱买房，马上女儿长大了。感觉没有赚钱的
突破口。这种心理会让人产生一种不安定的状态，在这个状态下很难干好事情。
负面心理大永远是一个不好的事情，智商永远是好的事情。Tip .靠，这想法是
大脑想出来的，当然是这样了。然而负面心理对于解决事情没有帮助，但对于提
升感觉，灵感是极好的。我想一个历害的人永远是很强的大脑加上很灵敏的感觉。

有各种心理不可怕，有各种想法就可怕。想法需要去控制去澄清，一段时间内只
干一件事。

有一些心理出来了是需要去压制的。但前提是先出来，再去压制。

思路不开的事候，喝咔啡。
** Memory 与ＩＱ
ＩＱ产生的是一些想法，想法不一定很值钱，值钱的是想法加上记忆，也就是连
贯起来的想法。记忆很重要。

想法，可以灵活可以澄清，但不可想太多。想法并没错，可是加上了心理上的误
区，人就会想太多，钻牛角尖。

想法，要注重换位，可分层次思考。
** 要强
今天是科比的最后一场球，告别赛。科比在联盟中不算是最有天赋的那一level，
但是现在就他打出的成绩，在历史上也能排出个前几了。他靠的是什么？别个问
他为什么这么历害，他说：“你们见过洛杉机凌晨4,5点钟的太阳么？”。他说过：
“总得有人赢，那为什么不是我呢？”。重点有于这句，“为什么不是我？“，我认
为这是一个人要强的根本，想赢，而且认为应该赢。通常我也是，有时候在某些
方面输给了某些人，特别是输给了那种不觉得很强的人，就感觉想不通，不能接
受。觉得：“为什么我赢不了他”。每每这么想，每每就没有安全感。结论，为什
么不能是我赢是每一个好强人的共同思维，而好强的最根据原因是安全感，认为
只有赢了才会有安全感。


老何今天要我写关于流程的文档，并且把ＥＤＡ流程脚本上传ＳＶＮ，这让我很
不情愿。分享是一件需要经过别人同意的事情。感觉这是被压迫的事情，并非自
己情愿。很多事情是要事先说好的，不是说临时决定，想怎样就怎样，这样会让
别人感受不到尊重。
** 关于心理与人生态度误区
令天是星期一，经过了周未的放松与转换之后。先说说我的感觉：”有一种感觉
就是感觉，脑袋不够用了，怎么说呢，上班看到一些烦杂的事情，觉得这些事情
发散开来处理不尽，就算能处理尽，但也是费时费力，不值当。“

其实这个感觉不是一次有了，好像一直都会有，发生于精力不足，脑力跟不上，
或是情绪低落的时候。放假归来上班时，就挺明显的，第一天上班，周未把精力
耗光，然后面对一些丢掉两天没处理的问题，就觉得力不从心。

人精力不好的时候有上面所述的感觉很正常，但是并不代表由这种消极精绪衍生
出来的想法就是对的。精力好的时候我们感觉什么都能完成，一切问题终将搞清
楚，我们花时间不骄不燥的研究是有极大的成就感和趣味的。

在笔记里，我就不把我怎么柳暗花明的经历说出来，直接说结论吧：
	1. 我要做的和能做的工作就是高清和我自己工作和兴趣相当的一切问题。不存在浪费时间一说，好好的享受时间，tack your time!
	2. 弄清问题是绕过去比较好，还是直接拿下比较好？有一些问题是越清楚越好，有一些问题是我们选择不清楚，绕过去，因为绕过去更好。因为这些问题可以本身很重要，但实现这些问题的细节并不重要。
	3. 不存在因为难而不想面对的心理，心理上遇见感觉自己不能完成的事情就对本能的退缩，挫折，找理由。
	4. 解决这种心理的方法就是：想清楚（思考），不急（enjoy you time），喝点咖啡。
** 第一天写日记
我今天在microsoft onenote上写了我第一次打算坚持做的一件事，可以说是“笔
记”，也可 以说是坚持思 考与书写。我想没有一个词可以很好的说明这件事，
因些暂且将之复称为”笔记“吧，之后所有提到的“笔记”均指这个意思。说说与我
选择在microsoft onenote上写笔记的思考，后面 将提到我笔记的一个很重要的
因素，也是因为要记录思考，归纳记忆。
	1. 为什么我选择microsoft onenote，而不是之前也用过的emacs和有道云笔记？
	原因：我想一个好的笔记软件，最好需要具备几个功能要素：可以联网
	更新同步；方便富文本编辑；隐私安全性要高。emacs主要还是一个纯
	文本编辑软件，要达到方便笔记编辑更新，需要很多麻烦的配置，主要
	问题是麻烦。有道云笔记其实和onenote很像，但是总觉得国内的厂商
	做这个稳私保密不高，不如外国厂商工具来得可靠。

在笔记中，我想做到与达成的几件事。

不想好好做事，好好进步的原因？想到要做一件事，就马上想做这件事之前，最
好把另外一件事也做了，然后因为另外一件事不想做所以这件事也不想做了，最
后事也没做，还有一肚子后悔心里。

记录一下接下来需要做的几件事：定置好ＭＡＣ的emacs，使之能够进行org
-mode ＴＯＤＯ管理与latex beamer，html.(为了能够管理记录接下来的工作)。
建设aliyun设施，ＦＴＰ，Trac，apache。迁移pass-key。整理阅读之前笔记
（工作量较大，而且不 大愿意做），不大愿意做的原因，个人在记录笔记时总
以为记录了就是自己的了，不愿意在付出精力来再读一遍，再回想一遍。但其实
回想很重要，有一些记忆没有被记住，就是因为不好记，重复的记忆是一种最终
记住的重要方法，类似于有道词典。要想好记还一条路是不断的减化去想清。






