* from youdao
** 生活需要智慧
生活需要智慧，需要清晰，需要不断的审视虽然有时候，经历痛苦，硬抗没意义，
无谓针扎。但每一次挣扎就是一次尝试，每一次能够产生确信结果的尝试都是十
分有意义的。

人生只要积极尝试，自己去改变，使自己开心，保持清醒，乐趣，品味。

** 置身 人生格言

把自己投身与社会中并且获得优势！社会总是多变的，随时间变好，如何在时代
的浪潮中，放置自己并取得优势，身心，精神都适应这个社会。

** 心理优势
心理优势，现实中往往心理强大的人更容易成功，心理强大，首先要构筑心理优
势。需求管理，心理的满足往往来自于需求得到满足，心理满足了，优势了，是
最终目标。所以如何满足需求？如何构建心理优势？心理优势的优先级大于需求
管理。短暂的需求满足换来的心理亏损是划不来的。



心理优势在于能屈能伸，拿的起，放的下，承受不了的不要做，应该承受的要勇
敢放开心胸磨练。

** 天生骄傲与承受被操
天生骄傲与承受被操。天生骄傲是看的起自己，有品味，有追求。承受被操，是
有勇气，不断追求面对现实。

这两点是自己在做决定时需要考量的。

** 人与人之间
人与人之间，其实感觉很灵敏，是透明的，长时间相处，有些话不用表明，对方
也知道。

此时，我们不用急于表达自己，关键是做好自己，坚持自己。

** 愤怒

有时候感觉怒不可遏，这种情况一般有几种原因。一是自己很想要的得不到。二
是受委屈之后，不能确信自己是对的。案例分析：恼羞成怒，是自己错了，然后
被人侮辱。这时候会有别人侮辱我是不对的想法，已经不是事情本身的对错。所
以是因为得得不到尊严怒的。

当然这里排除自己知道自己是错了，还要生气的傻逼。

** 游泳与性 鱼水之欢  

突然发现，本来很强的性欲会在游泳后得到缓解。看来人的起源真是在水里。雨
水之欢也说的没错，女人似水也没错

** 努力与认真

努力不是认真，认真不一定是努力，认真一定有效，努力不一定有效。只是大部
分情况下努力的人都认真了，努力使的是蛮劲，认真使的是巧劲。

** 解决眼前的关键矛盾是生活的核心。
首先要发现眼前的核心矛盾。


矛盾1:不大会用非常正式的语言。例如，写报告，写专利。矛盾2:焦虑,想快速
 发财，每一天都在等待着发财。

** 人生活存在很多需求，大部分需求都是合理的。我们也为满足这些需求而活着。有时满足自己的，有时也需要满足它人的。

那作为一个男人，其实不仅要照顾好自己，同时肩负着满足他人

** 看到日本人，图书馆很多，看一些冷僻的自己喜欢的书根本不用买，图书馆省了不少钱，还能满足大家的需求。

我想中国现当代最追求，最至上的莫过于钱了，钱是能买到很多东西，但最简单
的莫过于拿钱买，钱买实为下策。如果社会不用花什么钱，大家能各取所需，我
想这样才是所谓发达吧！

** 多一点创造，多一点设计，人生没有什么是天然的。世界是不平的，但是公平的自然法则。

** people do what they want,they believe what they want to believe.
while face the truth,face to the facts is the only way to solve the
problem no matter you denied it or not.

** 日记 
38妇女节，我在这一天惹妇女生气了，原因是没有照顾她，我知道今天应该表示
下的，但是我最终想想没什么东西买，也就算了，但是她生气了，我也是没有办
法，要写论文。我想不写论文，以后便没有好的工作。我对现在这种困苦的生活，
本来就很不适应了，所以想写完论文，一切也就轻松了。今天，唯一比较好的是
心态好了些，至少 我做到了对，几件事情不发脾气了。感觉自己还是不能适应
压力大的生活，得好好再调整心态，对自己的心态还是很有信心的。今天想为什
么我的记忆总是跟不上自己的年龄，原因可能是自己从不用心去记自己的生活，
也不会写日记，心态也没成长，感觉天天面对同样的事情，不懂得思考，不懂得
承受。

** 欺骗
我尝试着不去欺骗自己，让自己平躺的放在现实的阳光下晒着，不久，心就被悲
伤，忧郁浸泡。 看来我还没有足够强大

** 思考
在我心里我其实一直都知道写日记是有助于思考的，但是一直都很急躁，本能的
想找个方式来解脱下。其实是逃避了。最终也没能在心里得到安慰。最近，我想
违约，想去工作。不知道钱能不能凑齐。不知道如何与老师说。走的话还有很多
东西要处理。这3个问题搞得我很烦躁。不能静下心来，就越是急躁。越是急躁
就越是很多事情没做。总之还是心态不好。看着别人都找到好工作，心中不服。
其实这不是不自信的表现。

** 你欺骗生活，生活就会欺骗你。
但生活中，怎么做的不欺骗，又完美生活。其实就是永远不欺骗自己，不去尝试
欺骗别人。

** 生活在于简单，追求。
品味非常重要，抓住哪些真正重要的。

** 女人觉得不色的男人性感。
欺骗，只能欺骗信你的人

** 今天看着这个高度合适的电脑，就很想玩魔兽，因为以前玩游戏的时候在一个差劲的高度玩的，由于玩的很久，搞得头晕眼花。于是在今天就想见证一下自己的真实实力。
  打的是不死族，发现只要后期给电脑机会，电脑就能赢。感觉有挑战就多玩了
几局。论文到晚上才看，自己一直喜欢做事找借口，这次发现媚媚在找借口，就
说了她。思考人活着太累了或者不想做那些事情，就想逃避。为自己找借口。但
无奈的是不想做也得做，所以遇到无奈就要把无奈变成自己想做的事，这才是心
理的强大，只有好好做才能解决问题了。之前在一篇感悟中写到，怎样才能洒脱，
就是没无奈，在面对选择，知道自己要什么，不知道的时候，要不犹豫，跟着感
觉走。做自己喜欢的事是自己的才能，做自己不喜欢的事是心理的强大。

** 最近一直想弄一个android或iOS的apk.
用git同步.内心也一直比较乱，对于现状比较煎熬，生活没有追求与方向。不知
道该做些什么，一天到晚浑浑噩噩。想着买个房子？没有钱，但也不一定真正能
解决问题。对很多事情提不起兴趣，却又不能平静下来。消耗很大。不明白人生
此阶段的意义。

** 有道是，能把自已的话完整的表达出来，是一个文化人必备之一。写出来或者说出来或者做出来。重要的须序是写出来>做出来>做出来。上面这个顺序对于我自己包括大部分都是适用的。
 说出来，当然不是自言自语，所以一定要有受众。有道是，言多必失。为什么？
 因为对人与对事是两个很不同的概念。对人需要考虑受众心理和自己的心理。
 自己在说的时候必然也想从别人那里获得反应，获得共鸣，获得验证。但另一
 方面，说出来又是上面三个方面中最最容易的，说的过程中不需要付出体力努
 力，如果信口说的话，连智力都不需要付出。写出来，如果不是天天发公众号，
 报纸上写的话，那么写出来就基本上就自己看了，同时也不需要别人太多的反
 馈，自己在写的时候能够圆上就行。退一步不能圆之也罢。但写出来好处很多，
 可以起到很好的思维整理的作用。俗话说，好记性不如烂笔头。钱学森，不做
 笔记不读书。写出来，在整理的同时加重了记忆，同时也能够有据可查。如果
 在一个事情记忆能够延长，那么就可以简化这个事情的理解，对于信息量大的
 学习是必要的方法。人的智力集中体现在短期的逻辑能力，长期的记忆，以及
 变化能力（try的能力）。做出来，唯一需要注意的是：1,在合适的时间就去做，
 跟随自已的心。2,相信长期见效的事情，坚持。念念不忘，只会口干。做做不
 忘，必有其响。说说面已，主要做人。

** 感觉自己的幼稚和懒惰是生活在一起的，学的很快来形容那些成熟的人。但，我学得很慢，这是我深深体会的。

** 不惧怕人，不怕事。

** 富有的并非拥有多，而是奢求少，人实现欲望的能力赶不上欲望，意味着痛苦

**  平平凡凡生活就是一种快乐

** 人说躁动，我想我现在就是躁动不安，浮躁。看很多事情都不想做，因为觉得很没意思。
沉不下气，事情也做不好，即便做了，也是骗自己。我自己心里是非常清楚的。
我想知道自己这种情绪的由来，从中找到解决办法。我知道安心工作，细心生活
是对的。现在我却看不上我的书。为什么！！！原因：
  1. 我觉得我不相信我自己，通过做事能达到想要的结果。
  2. 或者说结果现在在我看来微不足道。没有诱惑力。
  3. 懒，范懒，什么都不想干。
后注:不慌不急，叫做情商，也是对自己控制力的肯定。

** 有时候这个世界上的人就是喜欢南辕北辙，但事实却和想法相差很远。用智慧去战胜欲望！

** 今天听歌的时候突然，想到要单纯的评判一个音乐的好与坏并不容易。
有时候听起好听的歌，换了一个环境，也许听起来很刺耳。后来我领悟到也许音
乐就是一种心情，在合适的时候听合适的歌才会自在。我想这也就是不同的人喜
欢不同歌的缘故吧！

**     终于知道为什么爱情叫长跑了；一个在前面跑，一个在后面追，合拍了就在一起，是一个淘汰的过程。
    男人，拿得起，放得下。克服恐惧的方法，就是直面它。男人要站起来，自
    己活。以前无论对或错。我总是思考别人的感受。现在我要做一个对的人，
    做对的事。不去理会那些没有弱小心理。心理不成熟是苦恼的根源。我往往
    不能接受别人对自己的批评与不重视。太自我了。我的欲望很强烈。我总是
    喜欢幻想美好的时光，幻想有时破灭或与实对比，难免苦楚。对快乐和令人
    欲望要求太急切了。我的特征就是缼爱与歇斯底里。已所不欲，匆施于人，
    对人友善，胸怀正气。瘾、与快乐的区别：瘾是欲望第一，原始兽性，与内
    心、心情无关，容易使人丧失理智；快乐是情感，即使没有在欲望上得到满
    足时，也可以快乐。理智上也可以得到满足。滋味就是快乐生活，笑品人生
    百味。做为一个平凡的人，自己的很多欲望还是要正视和满足的。然后渐渐
    的完善自己的情感。所以说快乐是内心情感和欲望的双重作用。怎么利用自
    己的想象力，怎么开发控制力。

** 只有输的起的人才能赢，只求做事，能放好心态。

** 我到现在更了解自己，没胆，不是敢爱敢恨。

** 人不要懒，心里想着自己要做的事就去做

** 不努力，我不知道未来

** 先跟着感觉走，然后再思索感觉

** 真的，有些人是笨人，有些人是丑人。
有人说人的这些特征是天真决定的，其实这个说法只猜中了两个特质中的一个。
这两个特质是，第一，笨人永远是笨人，因为他身上有一个永恒的东西。这是猜
中的那个说法。第二，笨人之所以为什么会选择成为笨人，是因为最初的那个想
法不一样，先入为主，很难改变倒不如说，不想或找不到理由去改变。其实只要
你秉持的理念变了，你就变了一个人。真的。

我之所以要学自私，就是想要改变自己的理念，变成一个聪明，平静的人。达到
一个美好状态的终极追求。但我现在的感觉是我只要追求自私，自爱，和自我意
识，我就能进步。不知为什！还有懒是不行的！

** 成为一个人，不是你环境的影响，不是你热爱什么样的人，最终他是一种内心的选择。
你内心选择成为什么样的人，最终你会变为那个人。其实我之前的选择是骄奢淫
逸，还要有别人的尊敬。现在想想真是可笑，不管我怎么努力聪明，方向错了，
就怎么也对不了。个人可以有享受，可以有要求，并且应该正视和满足。但不是
骄奢淫逸。不能永远选择懒。

** 保持想像力与观察力的统一

** think 平心而论

** what you believe concern to what man you will be

** 智慧
智慧=记忆力+思考力;不想事就范困。不是因为没睡好觉。

** deep in ,not just evaluate

** 欲望一次一次的被满足就会放大欲望，欲望一次一次被压抑就会减小，所以上帝就创造出成功和挫折来平衡人们的欲望。

** 没有人是不会害怕的
之前我以为勇气是天生的与生俱来就有。现在想想那些之前飞扬跋扈的人，其实
就是仗着自己那对环境的熟悉来欺负其它不了解环境的人。本来家就是强大，所
以自信就来了。因此，做人要识时务，不能乱来，有很多事情存在必然有其合理
的原因。不要相信别人天生来怎么怎么样那一套，自己其实本质上是不比别人差
的。每个人都是有很多共性的，很多人在弱势力的情况下，被欺负，想不通就认
为是自己不行，天生的，因此在心理上变的害怕、恐惧，其实也就是认为自己真
的不行了。其实那时，自己本人并不知道人就算一时不行也不带表事情没有转机、
一成不变。实际上往往相信能改变的人才能一直努力并真的实现逆转。人要相信
自己，即使不能。也要慢慢安慰自己。心理上要给人以鼓励，让人相信了再来实
现。对于事情可以就事论事。


最终，一个人成为什么样的人不是环境而是想法和心态决定的。

** 李爱信
我想我以后生了一个儿子，就给他取名李爱信，爱自己信自己。活自己的人生，
做自己想做的事。这样他便不会注意别人，好好的过自己的生活。

** 自己的晚上
晚上我总是很难睡着，心中不安，我觉得我怕，怕失去物质，怕自己没面子！其
实真的内心平静是最好的，做自己力所能及的事！不过分追求！用心生活！安心
生活就是智慧！

** 在欲望中生活
人的欲望是要满足的，就是在需要的时候。我就想啊，加入天天都生活在欲望中，
那应该很精彩很快乐吧。后来想想不对。其实这个道理就和食欲一样，你不能因
为饿的时候吃好吃的很满足，就一直去吃。找好吃的。这样最后不一定好。主要
是没必要。总是有满足和平静的时候。做人开心，快乐，容易满足，就很好。可
以很满足的时候就去用力享受，不可以的时候凭自己能力爱自己。

** 有时候我感觉我的父亲脾气很大，有些事只知其然不知其然，不知其所以然。感觉不对，就强迫性的让我去改。到后来也适得其反。
其实真正要明白的是其中的道理。知道为什么也就好了，不强求，这样心态也能
好。心态是生活的关键。

** 生活就是放轻松，用心去生活
我感觉自己，一直在压迫前列腺，不好，以后改改，轻松生活，不要让自己那么
急，没什么好处，也没什么用，男人就要有担当，生活在各种环境。越适应对自
己越有利。呵呵

** 贪婪的理解
贪婪是很2的，当你很满足的时候便沉醉进去不能自拔，不能有更大作为，更大
享受。就像早泄，一发不可收拾，享受做爱。用心爱爱。

** 蔡妍 一个人
听着前奏，很感人

** 关于结婚
我想我以后　肯定要找一个能使彼此都快乐的人，如果不能快乐，那还有什么意
义呢？希望自己慢慢觉醒，知道自己想要的是什么．以后谁也阻挡不了我的快乐。
包括我爸妈。

** 梁泳琪－凹凸
这首歌就是我现在心情的写照

** 怎么激情演讲
本身演讲的高潮已经想好，并且自己也为之激动

** 走入人内心，寻求平静

** 成长
不要害怕失去，也不要勉强。做事心先到。勇敢的面对自己的内心。

** 人生不要害怕吃亏，挫折。因为生活
吃亏，挫折是人生的正常变化。接受它~

** 哲学
什么 是哲学？就是你想就有，你不想就没有的问题。大凡想用自然科学来解释
哲学的理论就是瞎扯。生活是一张一吸，要懂得缩放。所以猥琐也是一种生活哲
学。懂得接受，懂得吸纳。

** 随笔
有时候，感觉有欲望会很痛苦，就会让自己不去想，因为自己的内心受不了这种
现实和理想的对比。所以这样的结果只有两种，要么自己妥协，要么自己内心强
大。在我看来内心强大已是不大可能，还是清心寡欲比较实际。内心的强大是需
要养的，需要呵护。follow your heart! no matter how bad it is!

** 生气
其实每次生别人气的时候，都是在生自己的气。自己没什么毛病也就不会对别人
的缺点看的那么重了。

** 选择与无奈
在生活中我们时常面临很多选择，也有很多无奈。通常在无奈中我们往往会想要
是有选择多好。在面临纠结的选择的时候我们往往会想选择太烦了。其实这就是
不好的想法。我认为在我们有选择的时候是好事，大方自由潇洒的去选择，人生
也很快乐。在我们面临无奈的时候要沉浸下来，心态放好，急也没用。在无奈中
好好生存。这才是我们要做的。

当然高品质的生活是选择会多些。但是那不是人人都能拥有的，我们能拥有的是
自己的生活。在无奈中平静，活好就无憾了。做好自己该做的事，不要有啥压力。

** 磨砺和锻炼
其实想要要使一个人变得更强大，有两种方法，一个是养，一个是磨砺，其实这
个是一个哲学。磨砺很容易就变成摧残，无论是从身体还是是从心灵上来说。而
养的话也很容易适得其反，比如说病的时候养是对的，好的时候养就变成胖子了。

命运就是你不能选择自己的路，比如说在你心灵很脆弱的时候又遇上了很重的负
担。这样就是摧残了。

我想这也就是乱世出英雄的原因吧，英雄往往能得到不断的锻炼，而和平时，心
灵强大的人只是养了，反而不行。但是太无能的人少了。

** 要能控制自己，对自己要好，但不要纵容
人为了不在很多的时候焦急，有准备的生活，就不能纵容自己，要能控制自己，
在行动上要求自己，对自己好些，不要让自己肆意任为。最终达到控制自己的目
的。平常该学习时，就学习，但对自己在生活待遇上要好些。该做啥就做啥。

** 什么是无奈？
无奈就是你觉的想法与现实产生了极大冲突时，你仍不相信现实就是合理或者说
现实就是自己的习性，这时候就会感到无奈。

** 对与错
很多时候对与错，应不应该根本不足以评价这个世界，其实喜不朝喜欢，爱不爱
才是最真。反正也不能怎样

** 不要想着去
不要想着去气别人，做自己

** 我这个人是哄不住的
，要什么我自己很清楚。当我得不到时总是难过，受伤，难过时候会放弃。减少
自己的伤痛。我想让自己冷静下来，开开心心做自己的事。做一个淡定有涵养的
自己。

** 要记住的话
自己是什么样就什么样，不要怕去展示，大度面对不足的自己。

** 心灵的强大才是真正地强大，做人要有宽广的心胸。
追求内心的平静！！！

** 我拥有勇气和死亡，但死亡确只拥有我。
我不能控制这个世界，唯一能控制的是我自己。做最好的自己。

** 做人，清楚明白，正直爽快。明白付出什么就收获，对此要有足够的信心。

** 我终于明白自己生气时，不理人。其实我是想给自己一个空间明白究竟发生了什么。对事不对人。
我幼稚，我不懂人性。心中不安，无法安静，没有安全感，没人爱。自己也恨自
己，不爱自己。爱安全感。

** 给人安全感的是人际关系

** 看清自己的欲望，把自己的欲望晒出来，为什么智慧可贵而欲望廉价，因为智慧具有花样，而欲望总是那样，赤裸裸。所有有欲望别不好意思。

** 我
今天我发现自己，为什么不愿意面对，总是逃避。我不喜欢限制，在一件事情上
不能坚持很久，不能坚持。我喜欢自由自在，想法总是跳跃。我之前说过要做一
个勇敢的人，就要不惧怕和人比，不怕输，在一件事上应该持之以恒。真的勇士
敢于直面惨淡的人生，敢于面对真实自己，敢于做真实自己。其实健身并不能勇
敢，抛弃自己的怯懦才是勇敢。我给自己一段时间专心做事，看自己能不能战胜。
不在为难事皱眉，做就是。

** 今天是星期一，但是对于去上班还是不大愿意，不知道去做什么。

** 不要害怕未知

** 勇
低级思考，思考我怎么不行－－－导致沮丧。高级思考，思考我控制好思考，不
考虑干扰项。－－－避免沮丧。

** 沮丧，勇，喜，恶
1,有人说，人体的血液太少，头脑和下体，只能提供给一个地方。因此想要好好
思考，需要做到这几点：专注，控制性思考（不能无控制思考，太累，注意修息，
持久战），沮丧（心理上不能受太多干扰和压制）。2,为了个很好的思考：● 果
断排除干扰项，以喜恶治沮丧。● 勇气，有勇气控制好思考这个武器来保护思考。
用喜来鼓历思考。

** 性与思想
其实，我压抑的是性和思考，佛洛依德说，人最原始的动力是性，当性得不到满
足时，会转向艺术的方向去表达。所以我想，其实1，有可能一个人思想伟大，
性压力就越小，因为他在思想上得到了表达。反之，天天只想性，性压力大的人，
思想可能越荒芜。2，不管是性还是思想，应该都是我们应该努力追求的。

** 
