* 真正的日记决不是为了写而写，而是自我在认识输出
* 每天自然而然的输出
想法本没有胆识

需要粗暴的拐弯吗？

我为什么么要干这个

我在做什么？

SB状态，睡一觉就废，起来忘了自己了

灵气是啥，自我在哪？怎么找不到？

对物质的追求是啥？

理解这个世界，沉定下来你看见的是啥？

颈椎头晕居然是用笔记本低头太多！

我是否想太多，是否在倾倒自已，宣泄。

倾倒自己--厌恶现状--我为何如此呢，讨厌现状

生活本是自由，却期望压制自己获得真实，压制本身就不真实。

意愿，何为意愿，压制是指压制意愿。

意愿如何产生，我不知道，不想知道，这本身就是意愿，嗯，就这样，自然。

你喜欢啥，你愿意啥，为啥会这样。

不自知便如是，日记是现在写的这个鬼吗？杂文？傻逼

削尖脑袋就是我这样的傻逼吧 ？

天然是啥？天然是不努力吗？

抽烟真心没用，好咖啡和红酒是真的有用

性感是啥？是欲望权力

何为雅--我就是人，人就是这样，无错

以前是收紧的状态，在这种急燥下，收紧有一些浪花，一些成事，但是否就是紧
导致的呢？

如果说每个人最终都是一个松的过程，那我有啥优势？我最终不也松了么？松就
是好么？还是说松紧适合恰当最好，那我之前那么紧怎么说？我是否是真的领先？
我怎么能与众不同？不同并不是我最准确的目标，我知道的是我不愿意与那些人
一样，一样太压抑，太搓。

很多事情你无法给其赋予价值，所以佻不会有热情，不会想做它，然面价值总是
在这些具体的事情之后，你会的这个东西，还要看其是否能被利用上，是否被需
要，人有时就是到了被需要才会想起其价值，自己并不会去主动的创造价值，因
为创造价值太难了，有些公司甚到不能创造需求，明确需求，刚开始需求并不明
郞，激历也无从下手，但是机会是一个挺主观的东西，不是所有人都能看见，一
个事有没有前途是所有事情需求的根源，人没有目标很容易陷入虑无意义状态，
门槛要非常低，你以为你跑的很快吗？没有目标的人是跑的很慢很慢的，停下来
想好像也不能解决跑的慢的问题，需求没有一个结构，没有连续不断的需求，就
没有连续不断的动力，除了需求之外其它的动力，我认为可能是狂热的兴趣爱好，
一般人没有，只有一点点爱好，很容易放弃的爱好，很容易妥协，驱动力有限。

老是站着不动，光想，也不行，想干出点啥事情,走的远者是真的，好像不能不
就是一个idea就能成。

现在没有用行动去录找目标，就是我的错，委屈我了，为了暂时一点钱。

要好好的把目标归整一下，你做那些事的目的是啥，有些东西单纯吃苦，吃苦有
时是没有意义的，还是要客观看待因果，单纯从提高能力角度出发，感觉不太好
弄，能力是一个项目培养和补漏的过程，有经验的成份。

感觉合理的行动才是最关键的，意想与现实可能很不一样，一定要警惕意想意淫，

发散是有意义的，本身是一个传感器，是一个感知力的体现，能更加接近现实，
有时候一些欲望会盖住一些事情的意义，使你浮于表面，也不想往下想，当然根
本是想法问题，没有一个对的想法，建立自己一个对的想法。

建立对的想法的能力需要训练和精进，真的能思考，感知，看见，真正分清什么
是真实和角度。

先看有啥，再看为啥，一个点一个点去记去清除，看问题回到问题，会发散，会
收敛，思考问题发散，解决问题收敛。

践行比重很高，很重要。

你与别人唯一不一样的地方就是思考行动与自我，过程的不一们决定了你是谁，
人生的过程是不可逆的，过程重要在这个地方才能体现。

情绪像一个封闭的坑，很多没有用，没用的情绪不能沉浸其中，因为此时你的
sensor已经不作用了,只能考理性思考跳脱，是一种非常危险的境地。但有一些
情绪将你引入另外一个环境，另外一个视角，使你看见了你平时看见不了的东西，
加强了你的sensor，这种是好的。

自我就是上帝视角，上帝视角不是第三人称，是高一层次的视角。

从那个视角来看，有一些事可能就没有那么开心和想像预期是不一样，这就是生
活，对生活预期本身就是有偏差的，这种预期的不准确贯穿在生活的各个方面，


所有框架的意义，所做事情都想把事情规整一遍，逆熵的过程。

活到现在才明白，有一些人虽然天天见，但是死活与你无关的。

人生的意义是飘乎的，一个合理的驱动力异常关键。

人总是在自我与傻我状态之间游离，自我状态不能延续，自我会忽进忽出，不能
常常感受自我存在，将自我带入当前即为更真实的理解--惨淡人生

自我经常处于脱离，导致与真实世界脱离，自我世界是和理解相关，所以没有绝
对真实，只有相对真实。人的世界就没有绝对真实，自我世界中才会有意义的存
在，这能让你意识到趣味，能力。傻我世界有欲望，充满了情绪。

人需要在客观世界中找到自我，自我的强大与否与人和客观能力直接相关，自我
与忘我的统一是很难的，是一个分清真假的过程。

2B世界提供一个感官sensor，感受世界，我好像从小感受的能力就很强，但又很
懒。自我缩在2B后面观察，2B世界很重要，是人根本的传感器。但是不能因为味
道就没有自我，自我的能驾驱2B，2B要健康不能压抑。中国人是客观，但同时又
是自卑的，想客观却又太接受自己的渺小，苟活的性格。

当今社会2B世界经常被媒体垃圾填满，不能正常sensor。丢失的2B世界，很多情
况下会造成自我丢失或不准。

客观，多角度，理性，被操，这些才能保证2B世界传感器灵敏，人活着为了啥是
自我意识启始，自我在呼唤认识自我，看见自己，成为自己，成就自己，人生就
是上下结合，上半身与下半身结合。

我现在状态可能有90%进间，自我是迷乎的，人性是深刻的，单个人并不深刻，
当然自我需要成长，不然太弱，看不见也正常

通透的人生，想清楚很多事

有时候没法思考或没有时间思考或拒绝思考是个大问题，一定要找到思考的办法。
